---
title: "Lions Stats"
author: "Jordan Roesch"
date: "2024-10-24"
output: pdf_document
---





```{r}
library(tidyverse)
library(coda)
```


```{r}
data <- read.csv("NEW_updated_model_data.csv")
```


```{r, echo=TRUE, message=FALSE, warning=FALSE}

modelString <- "
model {
  ## Sampling
  for (i in 1:N) {
    y[i] ~ dnorm(beta0 + beta1*x_Offense_TotYd[i] +
                 beta2*x_Defense_TotYd[i] +
                 beta3*x_Offense_TO[i] +
                 beta4*x_Defense_TO[i] +
                 beta5*x_Team_Score[i] +
                 beta6*x_Opponent_Score[i], invsigma2)
  }
  
  ## Priors
  beta0 ~ dnorm(mu0, g0)
  beta1 ~ dnorm(mu1, g1)
  beta2 ~ dnorm(mu2, g2)
  beta3 ~ dnorm(mu3, g3)
  beta4 ~ dnorm(mu4, g4)
  beta5 ~ dnorm(mu5, g5)
  beta6 ~ dnorm(mu6, g6)
  invsigma2 ~ dgamma(a, b)
  sigma <- sqrt(pow(invsigma2, -1))
}
"

# Data preparation
y <- as.vector(data$Win)
x_Offense_TotYd <- as.vector(data$Offense_TotYd)
x_Defense_TotYd <- as.vector(data$Defense_TotYd)
x_Offense_TO <- as.vector(data$Offense_TO)
x_Defense_TO <- as.vector(data$Defense_TO)
x_Team_Score <- as.vector(data$Team_Score)
x_Opponent_Score <- as.vector(data$Opponent_Score)
N <- length(y)

the_data <- list(
  "y" = y,
  "x_Offense_TotYd" = x_Offense_TotYd,
  "x_Defense_TotYd" = x_Defense_TotYd,
  "x_Offense_TO" = x_Offense_TO,
  "x_Defense_TO" = x_Defense_TO,
  "x_Team_Score" = x_Team_Score,
  "x_Opponent_Score" = x_Opponent_Score,
  "N" = N,
  "mu0" = 0, "g0" = 1,
  "mu1" = 0, "g1" = 1,
  "mu2" = 0, "g2" = 1,
  "mu3" = 0, "g3" = 1,
  "mu4" = 0, "g4" = 1,
  "mu5" = 0, "g5" = 1,
  "mu6" = 0, "g6" = 1,
  "a" = 1, "b" = 1
)

# Initial values function
initsfunction <- function(chain) {
  .RNG.seed <- c(1, 2)[chain]
  .RNG.name <- c("base::Super-Duper", "base::Wichmann-Hill")[chain]
  return(list(.RNG.seed = .RNG.seed, .RNG.name = .RNG.name))
}

# Run the JAGS model
library(runjags)
posterior_MLR <- run.jags(
  modelString,
  n.chains = 1,
  data = the_data,
  monitor = c("beta0", "beta1", "beta2", "beta3", "beta4", "beta5", "beta6", "sigma"),
  adapt = 1000,
  burnin = 5000,
  sample = 5000,
  thin = 60,
  inits = initsfunction
)


```



```{r, echo=TRUE, message=FALSE, warning=FALSE}
summary(posterior_MLR)
```




```{r, echo=TRUE, message=FALSE, warning=FALSE}
plot(posterior_MLR, vars = c("beta0", "beta1", "beta2", "beta3", "beta4", "beta5", "beta6", "sigma"))
```

```{r, echo=TRUE, message=FALSE, warning=FALSE}
post <- as.mcmc(posterior_MLR)
post %>% as.data.frame %>%
gather(parameter, value) -> post2
ggplot(post2, aes(value)) +
geom_density() + facet_wrap(~ parameter, ncol = 3) +
theme(strip.text.x = element_text(size=8))
```



```{r}

library(plotly)

```







```{r}
# Extract posterior samples as a matrix
post_samples <- as.matrix(posterior_MLR$mcmc)

```


```{r}
predict_mlr <- function(new_data, post_samples) {
  # Extract coefficients and sigma from posterior samples
  beta0 <- post_samples[, "beta0"]
  beta1 <- post_samples[, "beta1"]
  beta2 <- post_samples[, "beta2"]
  beta3 <- post_samples[, "beta3"]
  beta4 <- post_samples[, "beta4"]
  beta5 <- post_samples[, "beta5"]
  beta6 <- post_samples[, "beta6"]
  sigma <- post_samples[, "sigma"]
  
  # Calculate the linear predictor for each posterior sample
  lp <- beta0 +
    beta1 * new_data$x_Offense_TotYd +
    beta2 * new_data$x_Defense_TotYd +
    beta3 * new_data$x_Offense_TO +
    beta4 * new_data$x_Defense_TO +
    beta5 * new_data$x_Team_Score +
    beta6 * new_data$x_Opponent_Score
  
  # Sample predictions based on the linear predictor and sigma
  y_pred <- rnorm(length(lp), mean = lp, sd = sigma)
  
  return(y_pred)
}

```



```{r}
new_data <- list(
  x_Offense_TotYd = 390,    # Example values
  x_Defense_TotYd = 490,
  x_Offense_TO = 0,
  x_Defense_TO = 0,
  x_Team_Score = 24,
  x_Opponent_Score = 36
)

```



```{r}
predictions <- predict_mlr(new_data, post_samples)

```



```{r}
# Summarize predictions
summary(predictions)

# Visualize predictions
hist(predictions, breaks = 30, main = "Predicted Distribution", xlab = "Predicted Value")

```


```{r}

sum(predictions > 0)/5000



```


```{r}
update_model <- function(previous_posterior, current_data, new_game) {
  # Extract posterior samples from the previous model
  post_samples <- as.matrix(previous_posterior$mcmc)
  
  # Update priors with posterior mean and variance
  post_means <- colMeans(post_samples)
  post_vars <- apply(post_samples, 2, var)
  
  current_data$mu0 <- post_means["beta0"]
  current_data$g0 <- 1 / post_vars["beta0"]
  
  current_data$mu1 <- post_means["beta1"]
  current_data$g1 <- 1 / post_vars["beta1"]
  
  current_data$mu2 <- post_means["beta2"]
  current_data$g2 <- 1 / post_vars["beta2"]
  
  current_data$mu3 <- post_means["beta3"]
  current_data$g3 <- 1 / post_vars["beta3"]
  
  current_data$mu4 <- post_means["beta4"]
  current_data$g4 <- 1 / post_vars["beta4"]
  
  current_data$mu5 <- post_means["beta5"]
  current_data$g5 <- 1 / post_vars["beta5"]
  
  current_data$mu6 <- post_means["beta6"]
  current_data$g6 <- 1 / post_vars["beta6"]
  
  # Update gamma parameters for sigma (optional)
  current_data$a <- 1 + nrow(post_samples) / 2
  current_data$b <- 1 / mean(post_samples[, "sigma"]^2)  # Adjust if needed
  
  # Add new game data
  current_data$y <- c(current_data$y, new_game$Win)
  current_data$x_Offense_TotYd <- c(current_data$x_Offense_TotYd, new_game$Offense_TotYd)
  current_data$x_Defense_TotYd <- c(current_data$x_Defense_TotYd, new_game$Defense_TotYd)
  current_data$x_Offense_TO <- c(current_data$x_Offense_TO, new_game$Offense_TO)
  current_data$x_Defense_TO <- c(current_data$x_Defense_TO, new_game$Defense_TO)
  current_data$x_Team_Score <- c(current_data$x_Team_Score, new_game$Team_Score)
  current_data$x_Opponent_Score <- c(current_data$x_Opponent_Score, new_game$Opponent_Score)
  
  # Run the updated model
  updated_posterior <- run.jags(
    modelString,
    n.chains = 1,
    data = current_data,
    monitor = c("beta0", "beta1", "beta2", "beta3", "beta4", "beta5", "beta6", "sigma"),
    adapt = 1000,
    burnin = 5000,
    sample = 5000,
    thin = 60,
    inits = initsfunction
  )
  
  return(updated_posterior)
}


```




```{r}
new_game <- list(
  Offense_TotYd = 390,
  Defense_TotYd = 268,
  Offense_TO = 0,
  Defense_TO = 0,
  Team_Score = 24,
  Opponent_Score = 6
)

```



```{r}
posterior_MLR_updated <- update_model(posterior_MLR, the_data, new_game)

```

```{r}
new_data_2 <- list(
  x_Offense_TotYd = 405,
  x_Defense_TotYd = 301,
  x_Offense_TO = 1,
  x_Defense_TO = 0,
  x_Team_Score = 23,
  x_Opponent_Score = 30
)

```


```{r}
posterior_MLR_updated__ <- as.matrix(posterior_MLR_updated$mcmc)
```




```{r}
predictions_2 <- predict_mlr(new_data_2, posterior_MLR_updated__)
```


```{r}
hist(predictions_2, breaks = 30, main = "Predicted Distribution", xlab = "Predicted Value")
```


```{r}
sum(predictions_2 > 0) / 5000
```



